<?php
$DB_DNS='mysql:host='.DATABASE_HOST.';dbname='.DATABASE_NAME;
$option=[
    PDO::MYSQL_ATTR_INIT_COMMAND =>'SET NAMES utf8',
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_EMULATE_PREPARES=>false
];
$db = new PDO($DB_DNS,DATABASE_USER,DATABASE_PASSWORD,$option);